name: 'Trivy Vulnerability Scanner'
description: 'Scan container image for vulnerabilities with Trivy'
author: 'Aqua Security'
inputs:
  image-ref:
    description: 'image reference'
    required: true
  exit-code:
    description: 'exit code when vulnerabilities were found'
    required: false
    default: '0'
  severity:
    description: 'severities of vulnerabilities to be displayed'
    required: false
    default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
  format:
    description: 'output format (table, json)'
    required: false
    default: 'table'
  version:
    description: 'version of Trivy to use'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'docker://docker.io/aquasec/trivy:${{ inputs.version }}'
  args:
    - 'image'
    - '--format=${{ inputs.format }}'
    - '--exit-code=${{ inputs.exit-code }}'
    - '--severity=${{ inputs.severity }}'
    - '${{ inputs.image-ref }}'
