name: 'Aqua Security Trivy'
description: 'Scans container images for vulnerabilities with Trivy'
author: 'Aqua Security'
inputs:
  scan-type:
    description: 'Scan type to use for scanning vulnerability'
    required: false
    default: 'image'
  image-ref:
    description: 'image reference(for backward compatibility.)'
    required: true
  scan-ref:
    description: 'Scan reference'
    required: false
    default: ${{ inputs.image-ref }}
  exit-code:
    description: 'exit code when vulnerabilities were found'
    required: false
    default: '0'
  ignore-unfixed:
    description: 'ignore unfixed vulnerabilities'
    required: false
    default: false
  severity:
    description: 'severities of vulnerabilities to be displayed'
    required: false
    default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
  format:
    description: 'output format (table, json, template)'
    required: false
    default: 'table'
  template:
    description: 'use an existing template for rendering output (@/contrib/sarif.tpl, @/contrib/gitlab.tpl, @/contrib/junit.tpl'
    required: false
    default: ''
  output:
    description: 'writes results to a file with the specified file name'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://docker.io/aquasec/trivy:latest'
  args:
    - '${{ inputs.scan-type }}'
    - '--format=${{ inputs.format }}'
    - '--template=${{ inputs.template }}'
    - '--exit-code=${{ inputs.exit-code }}'
    - '--ignore-unfixed=${{ inputs.ignore-unfixed }}'
    - '--severity=${{ inputs.severity }}'
    - '--output=${{ inputs.output }}'
    - '${{ inputs.scan-ref }}'
